### ISSUE TITLE
Error converting module.ifo

### ISSUE THREAD

**Issue by ELadner** [niv/neverwinter.nim#10]
This is related to #4 I think.
I ran across an instance of a module that I can't round trip the module.ifo from GFF -> JSON -> GFF -> JSON
The second conversion to JSON results in failure.

The first module.ifo below came directly from an existing MOD file.
```
$ nwn_gff -p -i module.ifo -o module_first_json.json
$ nwn_gff -i module_first_json.json -o module_first_ifo.ifo
$ nwn_gff -p -i module_first_ifo.ifo -o module_second_json.json
/projects/neverwinter.nim/neverwinter/gff.nim(398) readStructInto
Error: unhandled exception: wanted to read 1024 but only got 239 while immediate-loading field Mod_ID of type Void on struct -1 [IOError]
$ grep -A3 Mod_ID module_first_json.json
  "Mod_ID": {
    "type": "void",
    "value": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
  },
$ ls -l module_second_json.json
-rw-r--r-- 1 eladner eladner 0 Aug 17 21:29 module_second_json.json
```
nim was 0.20.0.  neverwinter.nim project was up to date (pulled today, no changes, rebuilt tools for good measure).  Also tried with nim 0.20.2 (same results).

**Comment by niv** [comment]
Should be fixed as of 1.3.1
