### ISSUE TITLE
nwn_script_comp: Allow case-insensitive script parsing

### ISSUE THREAD

**Issue by Kalopsia-dev** [niv/neverwinter.nim#104]
It appears that modified base game includes loaded via the `--dirs` flag do not overwrite their original counterparts (from the `--root` directory) if the file name cases do not match.

Here is a more specific example:
- nw_i0_spells declares a GetRandomDelay method.
- We have moved this method to a separate include file, namely inc_generic.
- As a result, the nw_i0_spells file in our code base no longer declares the method.
- When compiling with nwn_script_comp, however, we get the following error:

```
D [2023-12-15T10:59:54] [1/4462] /scratch/scripts/ar_ck_gold700.nss: Successs]
D [2023-12-15T10:59:54] [2/4462] /scratch/scripts/g_isleaderdoor.nss: Successs]
D [2023-12-15T10:59:55] [3/4462] /scratch/scripts/ar_pl_mine.nss: Successs]
D [2023-12-15T10:59:56] [4/4462] /scratch/scripts/zdlg_criers.nss: Successs]
D [2023-12-15T10:59:56] [5/4462] /scratch/scripts/nw_s0_lsrestor.nss: Successs]
F [2023-12-15T10:59:56] [7/4462] /scratch/scripts/nw_s1_gazedoom.nss: inc_generic.nss: ERROR: DUPLICATE FUNCTION IMPLEMENTATION (GetRandomDelay) [via: X0_I0_SPELLS.nss(33) x0_i0_henchman.nss(63) nw_i0_plot.nss(23) inc_npc_store.nss(15) inc_generic.nss(24)]s]
```

I believe a flag for case-insensitive script name parsing would fix this, as our custom nw_i0_spells file would then be able to correctly override the base game one.

**Comment by mtijanic** [comment]
Are..are you sure that's what's going on? You're saying that it's not finding `nw_i0_spells.nss` when something does `#include "NW_I0_SPELLS"`?
I find that very hard to believe. Are you sure your resman priorities are set up correctly? Can you make a small repro case where you #include with both lowercase and uppercase and get different results?

**Comment by mtijanic** [comment]
I skimmed the nim resman and it looks like you're right - the directory search seems to be case sensitive. This would be a bug with all nim tools. @niv ?

**Comment by niv** [comment]
Yes, we've been talking offline and I asked Kalopsia to ticket this so it doesn't get dropped off the table again.
