### ISSUE TITLE
nwn_script_comp: v1.7.1 doesn't properly utilize threads

### ISSUE THREAD

**Issue by egebilecen** [niv/neverwinter.nim#109]
Hello everyone. So I have found a problem with new version 1.7.1 of script compiler. It doesn't properly utilizes threads. I will add pictures below that compares 1.7.1 with 1.7.0:

1.7.0 threads:
![1 7 0 threads](https://github.com/niv/neverwinter.nim/assets/29331682/5a500188-9ad6-449e-9742-7deb884f1cc4)

1.7.1 threads:
![1 7 1 threads](https://github.com/niv/neverwinter.nim/assets/29331682/f63b0559-2135-48e3-b815-61cf05fefd56)

1.7.0 cpu utilization:
![1 7 0 memory usage](https://github.com/niv/neverwinter.nim/assets/29331682/316608f2-d6c7-49e4-90a9-b01b36d882d7)

1.7.1 cpu utilization:
![1 7 1 memory usage](https://github.com/niv/neverwinter.nim/assets/29331682/b99d297b-9484-4eca-a11e-da11031582e2)

I have used both of the versions on same script directory which we have ~4400 scripts.

1.7.0 compiled all scripts in only 171 seconds:
![1 7 0 fast](https://github.com/niv/neverwinter.nim/assets/29331682/2c02ff48-4c09-4157-92fb-5e194082fd9e)

1.7.1 couldn't compile them all in more than 1 hour:
![1 7 1 slow](https://github.com/niv/neverwinter.nim/assets/29331682/9e298b5e-1b51-44e2-9347-ecdc76647ab1)

Commands used for each version is same and is the following:
`C:\Documents\Arelith\Developer\AreDev1.1.5\nwn_script_comp.exe -c --quiet --max-include-depth=64 --root "C:\Program Files (x86)\Steam\steamapps\common\Neverwinter Nights" --dirs C:\Documents\Arelith\Developer\AreDev1.1.5\are-resources\scripts\ C:\Documents\Arelith\Developer\AreDev1.1.5\are-resources\scripts`

**Comment by niv** [comment]
Regression bisected to 053a14ccc7e90670df93e346262f7cdf86ccdae0, both on nim 1.6 and 2.0

**Comment by ReachPW** [comment]
Having this problem in linux too.

neverwinter 1.7.0 (/2bff3b, nim 1.6.14)
![image](https://github.com/niv/neverwinter.nim/assets/61420975/68a37dac-b39a-4c81-ac37-d706513f7596)

neverwinter 1.7.2 (/48097e, nim 1.6.14)
![image](https://github.com/niv/neverwinter.nim/assets/61420975/45cf526a-a05e-4202-9990-2b87a1a29f75)

Tried with both `-j 28` and without `-j` for both.  1.7.0 takes slightly under  5 seconds, 1.7.2 was took more than 2 minutes before I manually killed it.
