### ISSUE TITLE
Spurious `mod` extension in gff resource list

### ISSUE THREAD

**Issue by LaputianBird** [niv/neverwinter.nim#24]
https://github.com/niv/neverwinter.nim/blob/f41a371a2e8d80604d35818747dd4b14d3a8da9d/private/shared.nim#L23

I don't think the `mod` extension is supposed to be there.

More details on discord: https://discordapp.com/channels/382306806866771978/382306806866771980/759917420772589585

**Comment by niv** [comment]
Yep, no idea why that is in that list.
