### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by ghost** [niv/neverwinter.nim#28]
I use Python, so I did not understand at all how this thing would help me. I got my nim compiler now to the latest (the one on my system was 1.0.6, which is why nothing worked). Now I see, it support JSON, and sqllite. That, is radical. Is there any kind of way to compile nim to C, and use it in python as a module? The problem is PyNWN is so old it is time to upgrade things. Thanks. Nimble says you can compile to C, but I am very new to Nim and have no idea what in the world to do yet.

**Comment by squattingmonk** [comment]
It's possible to use Nim with Python using [nimporter](https://github.com/Pebaz/Nimporter). The question is why? What kinds of things are you looking to do that would require using Python rather than Nim?

**Comment by neuralSKULL** [comment]
I am interested in Nim for long while. I do not understand many things about Nm at all, how the culture of the language. What tools they like. It is a very new language. I will look at nimporter, but I could use the CLI now and generate all kinds of formats for it. I have used python for long time, so I know the PEP and all the culture.

**Comment by neuralSKULL** [comment]
I gave up trying to use nimporter, as I don't understand much of the errors. I don't undestand how it works, and I am not at all yet familiar enough with Nim. If you figure out and can post direction on how to nimporter, I would love that. Thanks.

**Comment by darkSKULL-labs** [comment]
Ok, I learn now how to integrate it into Python. To do it, you must tell neverwinter.nim CLI to use JSON format. Then, we can do our edits with Python, and have the CLI return them to GFF. I tried to nimporter it but it has many issue, like typeless variable can't be Pythonized, and I gave up.
