### ISSUE TITLE
Add hint to help of nwn-gff and nwn_tlk, what encoding names is available

### ISSUE THREAD

**Issue by Mingun** [niv/neverwinter.nim#3]
At the moment this information is not clear and it is necessary to look in the source code to understand what encodings are available. I suggest to add the new command line option outputting the list of all supported encodings

**Comment by KevinBlue18** [comment]
I agree *nwn_ gff* not reading **bic** files, or am I missing something.

**Comment by WilliamDraco** [comment]
The help text has included the supported formats for some time now. Suggest this old issue can be closed.

**Comment by niv** [comment]
If you are talking about charset encodings, those are are provided by the OS and should be queried there!

If you are talking about gff file types, it's as said above.
