### ISSUE TITLE
 When Float is without decimals, it generates a conversion error

### ISSUE THREAD

**Issue by julien-lecomte** [niv/neverwinter.nim#33]
Initially opened as https://github.com/squattingmonk/nasher/issues/78

When filtering json through "jq", integer floats (0.0, 1.0, ...) are converted to integers without decimals (0, 1, ...)

This blocks the packing of the module with an error as ` Error: Could not convert src/ux/areas.tpl/area_technical.git.json` to `area_technical.git: {"type":"float","value":0}`

This error could be ignorable by being tolerant and treating int as float: 0 as 0.0, etc...

**Comment by niv** [comment]
Thanks.
