### ISSUE TITLE
Mass convert from json to gff-file not working?

### ISSUE THREAD

**Issue by dunahan** [niv/neverwinter.nim#35]
Today I tried to convert all my json-files in my github folder structure by batch and a for loop, but it throws an error. Below I wrote my syntax and following the error message:

```batch
for /r E:\data\mod\ %%i in (*.json) do (nwn_gff -i %%i -o %%~ni)

E:\data>(nwn_gff -i E:\data\mod\uts\sample.uts.json -o sample.uts )
parsejson.nim(522)       raiseParseErr
Error: unhandled exception: E:\data\mod\uts\sample.uts.json(1, 0) Error: { expected [JsonParsingError]
```

Is my attempt the right way to do this mass conversion?

**Comment by niv** [comment]
Check that sample.uts.json has valid json data in it. If it does, post the file please.

**Comment by dunahan** [comment]
Hm, at the next attemt it worked... Don't know what I have done wrong. The first time, it created a file with zero byte size and then I copied my sources again. Then I tested it again, so I see if the files are correct.  Thank you for your response ;)
