### ISSUE TITLE
nwn_gff Expectation failed: not hasKey(into.fields, lbl)

### ISSUE THREAD

**Issue by jakkn** [niv/neverwinter.nim#40]
I've run into a bic assertion error and need some help understanding what's wrong. I'm using `nwn_gff` to go from `bic` to `json`. The command completes successfully if I use any of the standard localvault `bic`s, but when I use `bic`s from my servervault the conversion will sometimes fail. Logs:
```log
$ nwn_gff --version
[...]
neverwinter 1.4.5 (/955f9e, nim 1.4.8)

$ nwn_gff -i /tmp/aluviandarkstar.bic -l gff -o test.json -k json --verbose
D [2021-09-28T21:11:14] NWN file encoding: windows-1252
D [2021-09-28T21:11:14] Other file encoding: UTF-8
gff.nim(379)             readStructInto
Error: unhandled exception: Expectation failed: not hasKey(into.fields, lbl) [ValueError]
```
Failing bic: [aluviandarkstar.bic.gz](https://github.com/niv/neverwinter.nim/files/7246731/aluviandarkstar.bic.gz)

Any idea what's wrong?
What purpose the lbl expectation serve?

**Comment by niv** [comment]
As discussed on Discord, GFF has a duplicate label entry. This is, strictly speaking, invalid GFF. However, the code could be amended in a suggested change to deduplicate field labels on read, as long as the labels match.

Origin of this duplicate label is _probably_ someone calling GffAddCExoString() in nwserver/nwnx twice.

**Comment by jakkn** [comment]
Invalid GFF caused by improper reuse of the field `NWNX_POS` by [nwn-dotnet/Anvil](https://github.com/nwn-dotnet/Anvil). Fixed there.
