### ISSUE TITLE
possible issue with latest version

### ISSUE THREAD

**Issue by ELadner** [niv/neverwinter.nim#44]
Seeing a failure in the latest version that works fine on an older version (1.4.2)

```
Error: Could not convert C:\Users\xxxx\Documents\Neverwinter
... Nights\modules\Arabel\acb_room_name.dlg: fatal.nim(53)
... sysFatal
... Error: unhandled exception: value out of range: 4294967295 notin
... -2147483648 .. 2147483647 [RangeDefect]
```

possibly this:

```
        "Delay": {
          "type": "dword",
          "value": 4294967295
        },
```

Either that value is out of whack, or maybe that needs to be an unsigned int?

**Comment by ELadner** [comment]
Odd.. I tested this in 1.5.4 on linux and it works fine.  My compatriot that's having the problem is on windows.

**Comment by niv** [comment]
Hm, probably a compiler issue, yea. Can you post or email me the .dlg?

**Comment by ELadner** [comment]
User downloaded pre-compiled binaries from the release page.   I asked him to download 1.4.2 (the same version I'm using) and it did error out on that file anymore.  _EDIT:  He must have downloaded 1.4.1 because I tested that version and it still failed as above._

[file.zip](https://github.com/niv/neverwinter.nim/files/8043970/file.zip)

**Comment by ELadner** [comment]
Verified this on my wife's computer.   says it's out of range (-2.1 billion to 2.1 billion) but typically DWORD values are unsigned ints, according to most references I've seen.

**Comment by ELadner** [comment]
Further testing:

This works with windows i386 on version 1.4.1 but fails in 1.4.2 (and up).
This is specific to the x86 version.  The 64-bit versions above 1.4.1 work as expected.

**Comment by niv** [comment]
Try https://github.com/niv/neverwinter.nim/releases/tag/1.5.5

**Comment by ELadner** [comment]
Worked like a charm.  Thanks!
