### ISSUE TITLE
Circular dependency detected

### ISSUE THREAD

**Issue by Script-Wrecked** [niv/neverwinter.nim#46]
Installation loops 'round and 'round...

$ nimble install neverwinter

...
/home/user/.choosenim/toolchains/nim-1.6.6/lib/impure/db_sqlite.nim(184, 1) Warning: Circular dependency detected. `codeReordering` pragma may not be able to reorder some nodes properly [User]
...

**Comment by niv** [comment]
This is a nim issue but it's harmless. You are seeing the message multiple times because it's compiling multiple binaries. Just give it a while.
