### ISSUE TITLE
nwn_twoda  clips id column

### ISSUE THREAD

**Issue by calgacus** [niv/neverwinter.nim#5]
When I use nwn_twoda to tranform a 2da file to a csv file the first column which, gives the data line number, is missing.  Is that deliberate or a bug?  I know the column is not important to the game engine but for humans trying to navigate around in multiple 2da files it is.

BTW, I tried to build-update to the latest version of these tools so could try to play with the code myself but I cannot get the latest version of nim to install with either  choosenim or with the latest nim package.

**Comment by niv** [comment]
The column isn't read as it contains no programmatically useful information (as you said, the game ignores it). I always presumed people use either text editor lines or something like Excel to orient themselves. I don't think putting them into the csv is the right thing to do - csv is data, not user presentation. Maybe a command line switch `--with-ids`, or something?

As to the build issue - can you be more specific? Try `choosenim update self` and then `choosenim install 0.19.4`.

**Comment by calgacus** [comment]
In a text editor the line number of the first data row is 1 not 0, so if a user is jumping around between related 2da files  like baseitems.2da and feat.2da then the numbers in the ReqFeat0 column won't quite match the line numbers seen in the csv file.   What I was doing was transforming the 2da file and then loading it into atom with a certain plugin to allow basic spreadsheet like viewing - instead of using a big spreadsheet app like Libre or Excel.    But anyway I can just use a shell script to do that so I don't need your program changed just for that, but if I can get nim updated maybe I could add that flag just for the heck of it.  

When I tried that I got:
 choosenim install 0.19.4
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: choosenim.nim(206)       choosenim
        ... choosenim.nim(187)       performAction
        ... choosenim.nim(89)        choose
        ... choosenim.nim(50)        chooseVersion
        ... choosenim.nim(17)        parseVersion
        ... Invalid version, path or unknown channel. Try 0.16.0, #head, #commitHash, or stable. See --help for more examples.


when I try:
choosenim update stable
   Updating stable
Downloading Nim 0.19.4 from nim-lang.org
choosenim.nim(206)       choosenim
choosenim.nim(183)       performAction
choosenim.nim(153)       update
choosenim.nim(34)        installVersion
download.nim(250)        download
download.nim(244)        downloadImpl
download.nim(192)        downloadFile
download.nim(177)        downloadFileNim
httpclient.nim(1302)     downloadFile
httpclient.nim(985)      parseBody
httpclient.nim(920)      recvFull
httpclient.nim(892)      reportProgress
download.nim(173)        onProgressChanged
terminal.nim(800)        showBar
terminal.nim(425)        eraseLine
oserr.nim(110)           raiseOSError
Error: unhandled exception: The handle is invalid.
 [OSError]

**Comment by niv** [comment]
I'll add a command line flag to optionally generate a ID column for exported formats.

Re: the choosenim issue, I am at a loss. Sounds like a choosenim bug. @dom96 might be able to help here, but it'd probably be best to report it over there: https://github.com/dom96/choosenim/issues
