### ISSUE TITLE
scriptcomp: Add constant folding optimization

### ISSUE THREAD

**Issue by mtijanic** [niv/neverwinter.nim#51]
Currently expressions like `n = 3+2;` and `s = "a"+"b";` actually generate two CONST and one ADD instruction always. These can be evaluated at compile time and replaced with a single CONST.

This is probably best done at codegen stage, when emitting an ADD (or similar) instruction, look back and see if the previous two are consts, and if so, just patch them up.

Alternatively, this can be done at a new postprocessing optimization pass, but that will require rewriting all jumps.

**Comment by niv** [comment]
nwnsc supports expression consts, such as:

`const int MINE = 1 << 3;`
`const int MINE2 = MINE  + 1;`

Supporting that is probably part of this improvement.

**Comment by mtijanic** [comment]
Dibs. Figured it out, just a lot of tedium to get all the operations handled.
