### ISSUE TITLE
scriptcomp: Add preprocessors such as #ifdef

### ISSUE THREAD

**Issue by Finaldeath** [niv/neverwinter.nim#56]
Having #ifdef and similar preprocessor commands as part of the standard compiler would be good since it means code can be supplied for engine, toolset or 3rd party compiler use and all 3 work, compared to running your own preprocessor which limits its use elsewhere.

My main use case is #ifdef to block out code which isn't needed unless, say, debug is enabled, speeding up compile and run times since you no longer have to have long strings added. Having #define would also be useful for use solely in #ifdef and similar although presumably in normal code would end up like any usual const value.

**Comment by mtijanic** [comment]
I propose that a better alternative is block-based dead code elimination:
```nss
const int DEBUG = 0;

if (DEBUG) {...}
else {...}
```
And the compiler discards the first block and makes the second one unconditional. 

Advantages:
- your code in the discarded block needs to be syntactically valid, so less lilely to bitrot
- can conditionally replace smaller bits of code that a full line
- optimizes all other such blocks where a feature is disabled
- removing `const` from the definition lets you change it to a runtime condition instead
- less confusing than figuring out which 5% subset of the C preprocessor is actually supported



Edit: of course, proper, full CPP support would be great, but that's a bigger task. Maybe integrate mcpp?

**Comment by mtijanic** [comment]
This is resolved by #124
