### ISSUE TITLE
scriptcomp fails to parse some float scalars

### ISSUE THREAD

**Issue by niv** [niv/neverwinter.nim#59]
```nwscript
void main()
{
  float a = 0.f; // ok
  float b = 0f; // ERROR: PARSING VARIABLE LIST
  float c = 0; // ERROR: MISMATCHED TYPES
}
```

Case b works fine on nwnsc, haven't tried case c; but I think both should be supported.

**Comment by mtijanic** [comment]
For the third case, nwscript design is incredibly/insanely type safe. You can't make it take an int literal without also taking an int const (and maybe int variable too), and I'm not sure that's desirable, given other patterns.

Ie do we want this to work?
```nss
int n = 3;
float f = n; // 3.0f
```
