### ISSUE TITLE
nwn_twoda.exe out of memory

### ISSUE THREAD

**Issue by calgacus** [niv/neverwinter.nim#6]
Am I doing something wrong?  I was experimenting with downloading csv files from google sheets.   You can upload a 2da file to sheets by just changing the extension to csv but when you later download the edited file and try to change it back to a 2da file it results in an out of memory error and a huge 2da file.

$ nwn_twoda.exe -i baseitems.csv -o "baseitems.2da" -k "2da" --csv-separator ","
out of memory
$ ls -lrt
total 16256
drwxr-xr-x 1 197609        0 Mar 28 10:48 ../
-rw-r--r-- 1 197609    25870 Mar 29 00:11 baseitems.2dax
-rw-r--r-- 1 197609    25518 Mar 29 00:26 temp.csv
-rw-r--r-- 1 197609    25870 Mar 29 00:50 baseitems0.csv
-rw-r--r-- 1 197609    25984 Mar 29 01:12 baseitems.csv
drwxr-xr-x 1 197609        0 Mar 29 01:13 ./
-rw-r--r-- 1 197609 16525676 Mar 29 01:13 baseitems.2da

The baseitems.csv file is here: https://docs.google.com/document/d/1bbNqVIzaROdaxNB_9-hNZK8fGR9jdkSZUPqP5qDZNBs/edit?usp=sharing

PS:  maybe this issue will help you find a bug and so be of some use but I just realized I can copy n paste directly from a 2da into a google sheet and back again with no need to run any conversion to or from csv.   I'll just need to change tabs to spaces and maybe trim excess spaces from the first few lines.

PPS: probably not of much interest to you but just for the sake of completeness I'll link this [related thread](https://forums.beamdog.com/discussion/comment/1057781/#Comment_1057781).

**Comment by niv** [comment]
Cannot repro on latest. Must have been fixed meanwhile, either in this library, or in nim ..
