### ISSUE TITLE
nwn_gff: json->gff fails if dword value > 2147483647

### ISSUE THREAD

**Issue by squattingmonk** [niv/neverwinter.nim#62]
When converting the [attached dlg file](https://github.com/niv/neverwinter.nim/files/12017251/dlg_convnozoom.zip) from json to gff, the following error appears:
```
/home/squattingmonk/Code/neverwinter/nwn_gff.nim(56) nwn_gff
/home/squattingmonk/Code/neverwinter/neverwinter/gffjson.nim(147) gffRootFromJson
/home/squattingmonk/Code/neverwinter/neverwinter/gffjson.nim(135) gffStructFromJson
/home/squattingmonk/Code/neverwinter/neverwinter/gffjson.nim(75) gffStructFromJson
/home/squattingmonk/Code/neverwinter/neverwinter/gff.nim(317) []=
/home/squattingmonk/Code/neverwinter/neverwinter/gff.nim(312) putValue
/home/squattingmonk/Code/neverwinter/neverwinter/gff.nim(286) newGffField
/home/squattingmonk/Code/neverwinter/neverwinter/gff.nim(248) assignValue
/home/squattingmonk/.choosenim/toolchains/nim-1.6.14/lib/system/fatal.nim(54) sysFatal
Error: unhandled exception: value out of range: 4294967295 notin -2147483648 .. 2147483647 [RangeDefect]
```
It is choking on the following section:
```json
"Delay": {
  "type": "dword",
  "value": 4294967295
}
```
Looks like it fails due to https://github.com/niv/neverwinter.nim/blob/4376a7b079f2ed6f6ffc2ec1ea15d4f413cb5d07/neverwinter/gff.nim#L228 introduced in e74f3fe.

**Comment by pethrowilo** [comment]
![Image](https://github.com/user-attachments/assets/7aa76ab1-e651-4b8b-b0c6-7ebd47d41c5b)

I've recently changed my nasher toolchain from a old version compiled with nim 1.6.16 to this version, and encountered this issue.
version of nwn_gff: neverwinter 2.0.3 (/081769, nim 2.0.2), neverwinter.windows.i386.zip.
this is an almost empty mod with default module config and a 2x2 empty area.

package with old mod succeeds, so might be .nasher/cache ignored files compiled before.

**Comment by tinygiant98** [comment]
@niv Did the windows.amd64 version not get built for the latest release?  edit: <https://github.com/niv/neverwinter.nim/actions/runs/13871519651/artifacts/2757368801> GHA shows it's built, but it's not present on the releases page for some reason.

@pethrowilo Vist the releases page and download the windows.amd64 version for release 2.0.2 and see if that works for you.

**Comment by pethrowilo** [comment]
@tinygiant98 confirmed neverwinter 2.0.2 (/165325, nim 2.0.2) windows.amd64 works fine.

**Comment by niv** [comment]
@tinygiant98 the mingw amd64 build has fseek stream issues still, so I have it omitted still.

I think the error here can be fixed on windows i386, but I have no way to test on my machine.

<img width="532" alt="Image" src="https://github.com/user-attachments/assets/86816018-cbe3-4ae1-bbc0-babdc3ca7f11" />

I have pushed a branch if anyone wants to try on a real Windows system (`nim -d:mingw --os:windows --cpu:i386`); https://github.com/niv/neverwinter.nim/tree/mingw-i386-gff
