### ISSUE TITLE
json format option for more filetypes?

### ISSUE THREAD

**Issue by calgacus** [niv/neverwinter.nim#7]
Would it be easy to add a json in/out format option to nwn_twoda (and any other filetypes not yet supporting json format if it would be at all useful but especialy nwn_twoda)?  Large 2da files, especially ones with many columns, editing them in a basic text editor is a pain, I was thinking of making a VS Code extension that would sit atop these tools.   I was poking at the old TlkEdit code but I'd rather be making something new.

**Comment by niv** [comment]
I'd suggest opening csv files in Excel, google sheets, or similar. json seems a poor fit for tabular data. Unless this is really important for tooling reasons, I'll not be adding json format compat to nwn_twoda.

I know this ticket is dead, but feel free to write back if this is still a consideration!
