### ISSUE TITLE
Windows releases have double ".exe.exe" extensions

### ISSUE THREAD

**Issue by ModifAmorphic** [niv/neverwinter.nim#91]
Windows releases have the .exe extension being added twice.

![image](https://github.com/niv/neverwinter.nim/assets/86930443/c9765e27-2c5a-4db8-b18a-abf375614a2e)

Release [1.6.1](https://github.com/niv/neverwinter.nim/releases/tag/1.6.1)
- [neverwinter.windows.amd64.zip](https://github.com/niv/neverwinter.nim/releases/download/1.6.1/neverwinter.windows.amd64.zip)
- [neverwinter.windows.i386.zip](https://github.com/niv/neverwinter.nim/releases/download/1.6.1/neverwinter.windows.i386.zip)

Fairly certain it's these lines in the release.yml workflow causing it.
[release.yml:72](https://github.com/niv/neverwinter.nim/blob/2749baab273483a89b4230d97b2881c1ac40c8fa/.github/workflows/release.yml#L72C22-L72C22)
`for f in bin/*; do mv "$f" "$f.exe"; done`
[release.yml:86](https://github.com/niv/neverwinter.nim/blob/2749baab273483a89b4230d97b2881c1ac40c8fa/.github/workflows/release.yml#L86)
`for f in bin/*; do mv "$f" "$f.exe"; done`

The nimble builds already output `.exe` files. No need to rename them.
`nimble build -d:release -d:mingw --cpu:amd64`
`nimble build -d:release -d:mingw --cpu:i386`

**Comment by WilliamDraco** [comment]
Niv is aware. It was a fix for an earlier issue where they generated without extensions that has since (apparently) been resolved upstream.

**Comment by ModifAmorphic** [comment]
Hi, just logging issue to help track. If this is already in another issue or addressed in a PR, then feel free to close. I didn't see one.

**Comment by niv** [comment]
Fixed in 1.6.2
