### ISSUE TITLE
nwn_script_comp: Info level logs sent to stderr instead of stdout in node

### ISSUE THREAD

**Issue by PhilippeChab** [niv/neverwinter.nim#97]
### Description

- I'm spawning a subprocess via node to compile files.
- Process exits normally.
- Logs that should be printed via stdout are printed via stderr. See below.

![5ad60adf27ccdb8e175916f6f6c22d05](https://github.com/niv/neverwinter.nim/assets/26422481/8d3f4e8b-4ec0-4686-acd8-eb6e377d8f05)

**Comment by mtijanic** [comment]
I don't really think _anything_ should go to stderr, should all just be stdout. Otherwise it'll be very hard to decide what goes where..

**Comment by PhilippeChab** [comment]
Failures to load a file from the system and similar errors should be printed via stderr, I believe. 

It's a minor issue, I don't have a hard opinion on the subject.

**Comment by niv** [comment]
The long-standing tradition of sending log/human output to stderr is to support the common unix usecase of `./my_command > outfile`.  When my_command errors out (exit code > 0), outfile will be empty. If the logs go to stdout, they'll instead end up in outfile AND the human operator won't even see them on the terminal.

**Comment by mtijanic** [comment]
Looks like GCC sends pretty much all output to `stderr` - Compile errors and warnings, and even `#pragma message "foo"` which is an info level print. I don't know what a good answer here is, so maybe we should just follow suite?

**Comment by niv** [comment]
stderr is bit of a misnomer in that it's not _just_ errors; that's in the POSIX standard as well as I understand it. The distinction here should be "user requested output" -> stdout vs "informational messages not part of the desired output" -> stderr.

Example: If the user requests to preprocess a file, the requested output is the preprocessed file content; and the info messages are all the warnings and pragmas.

Any further distinction would have to happen with explicit --pragmas-to FILE or something, I suppose.

**Comment by PhilippeChab** [comment]
> stderr is bit of a misnomer in that it's not _just_ errors; that's in the POSIX standard as well as I understand it. The distinction here should be "user requested output" -> stdout vs "informational messages not part of the desired output" -> stderr.
> 
> Example: If the user requests to preprocess a file, the requested output is the preprocessed file content; and the info messages are all the warnings and pragmas.

Thanks for the explication, it does make sense.

> Any further distinction would have to happen with explicit --pragmas-to FILE or something, I suppose.

Feel free to close the issue, it is not a blocker on my side.
